[build]
  command = "npm run build"
  publish = "dist"

[[forms]]
  name = "home-remodeling-leads"

  [forms.settings]
    # Send form submissions to your email
    to = "info@homeonpro.com"
    subject = "New Remodeling Lead from Raleigh Landing Page"

    # Custom email template
    template = '''
    New Home Remodeling Lead:

    Project Type: {{ project-type }}
    Budget Range: {{ budget-range }}
    Timeline: {{ timeline }}

    Contact Information:
    Name: {{ name }}
    Email: {{ email }}
    Phone: {{ phone }}
    Address: {{ address }}

    Additional Details: {{ additional-info }}

    Lead Source: Raleigh Landing Page
    Submitted: {{ created_at }}
    '''

[[redirects]]
  from = "/thank-you"
  to = "/?success=true"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"